name: "ECHONETLite2MQTT Home Assistant Bridge"
description: "This is an application for automatically discovering devices found by ECHONETLite2MQTT and exposing them as devices within Home Assistant."
version: "v1.14.0-1"
