name: ECHONETLite2MQTT Home Assistant Bridge
description: This is an application for automatically discovering devices found by ECHONETLite2MQTT and exposing them as devices within Home Assistant.
image: ghcr.io/nana4rider/hassio-e2m-hass-bridge
url: https://github.com/nana4rider/e2m-hass-bridge
slug: e2m_hass_bridge
version: v1.14.1-2
init: false
services:
  - mqtt:want
arch:
  - aarch64
  - amd64
watchdog: http://[HOST]:3000/health
schema:
  mqtt:
    broker: str?
    username: str?
    password: str?
  ha_discovery_prefix: str?
  log_level: str?
  echonetlite2mqtt_base_topic: str?
  description_language: list(ja|en)
  auto_request_interval: int
options:
  mqtt:
    broker: ""
    username: ""
    password: ""
  log_level: info
  description_language: ja
  auto_request_interval: 180000
