name: Docker build - e2m-hass-bridge
on:
  push:
    branches:
      - main
    paths:
      - e2m-hass-bridge/**
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - id: get-version
        name: Get Application Version
        run: |
          ADDON_VERSION=$(yq '.version' e2m-hass-bridge/config.yaml -r)
          echo addon version: $ADDON_VERSION
          echo "addon_version=$ADDON_VERSION" >> $GITHUB_OUTPUT

          APP_VERSION=${ADDON_VERSION%%-*}
          echo app version: $APP_VERSION
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/hassio-e2m-hass-bridge
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.get-version.outputs.addon_version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./e2m-hass-bridge
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ steps.get-version.outputs.app_version }}

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
